[BAHIR-97] Akka as a streaming source for SQL Streaming.
apache/bahir pull request #38
Opened 2017-03-27 04:56 UTC by sbcd90

This PR is created to propose the addition of Akka compatible streaming source for Spark SQL Streaming.

2017-03-27 04:56 UTC, ApacheBahir commented
Can one of the admins verify this patch?

2017-03-27 09:28 UTC, ktoso commented
Hi there, interesting patch :)
May I interest you with Akka Streams though? I think it would be the natural fit for the Akka side here. You could implement what you made Actors here as a GraphStage ( http://doc.akka.io/docs/akka/2.4.17/scala/stream/stream-customize.html ), and our blog series about how to write custom connectors ( http://blog.akka.io/integrations/2016/09/05/flow-control-at-the-akka-stream-boundary ).

Hope this helps! Would be super exciting to have a connection to Spark SQL Streaming directly exposed as Akka Source/Sink :-)

2017-03-28 00:08 UTC, lresende commented
Please test this Jenkins

2017-03-28 00:17 UTC, ckadner commented
ok to test

2017-03-28 00:18 UTC, ApacheBahir commented
Build failed, see build log for details

2017-03-28 00:18 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/34/

2017-03-28 00:20 UTC, ckadner commented
retest this please

2017-03-28 00:21 UTC, ckadner commented
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/35/console

2017-03-28 00:22 UTC, ApacheBahir commented
Build successful

2017-03-28 00:22 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/35/

2017-03-28 00:40 UTC, ckadner commented
Note, our Jenkins build server does not currently run Scalatests ...

> 17:20:55 No tests were executed.

```
17:20:54 [INFO] 
17:20:54 [INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ spark-sql-streaming-akka_2.11 ---
17:20:54 
17:20:54 -------------------------------------------------------
17:20:54  T E S T S
17:20:54 -------------------------------------------------------
17:20:54 OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
17:20:54 
17:20:54 Results :
17:20:54 
17:20:54 Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
17:20:54 
17:20:54 [INFO] 
17:20:54 [INFO] --- maven-surefire-plugin:2.19.1:test (test) @ spark-sql-streaming-akka_2.11 ---
17:20:54 [INFO] Skipping execution of surefire because it has already been run for this configuration
17:20:54 [INFO] 
17:20:54 [INFO] --- scalatest-maven-plugin:1.0:test (test) @ spark-sql-streaming-akka_2.11 ---
17:20:54 OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
17:20:55 Discovery starting.
17:20:55 Discovery completed in 36 milliseconds.
17:20:55 Run starting. Expected test count is: 0
17:20:55 DiscoverySuite:
17:20:55 Run completed in 100 milliseconds.
17:20:55 Total number of tests run: 0
17:20:55 Suites: completed 1, aborted 0
17:20:55 Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
17:20:55 No tests were executed.
17:20:55 [INFO]
```

2017-03-28 00:59 UTC, sbcd90 commented
Hello @ckadner ,
Are any actions need to be taken from my side? Like provide Java tests(Junits) instead of scala?

2017-03-28 01:30 UTC, lresende commented
retest this please

2017-03-28 01:31 UTC, ckadner commented
@sbcd90 -- Scalatests should be sufficient. We need to fix our Jenkins integration test setup. Not an action item for you :-)

2017-03-28 01:33 UTC, ApacheBahir commented
Build successful

2017-03-28 01:33 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/36/

2017-03-28 05:52 UTC, ckadner commented
retest this please

2017-03-28 05:53 UTC, ApacheBahir commented
Build failed, see build log for details

2017-03-28 05:53 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/37/

2017-03-28 06:51 UTC, ckadner commented
@sbcd90 -- can you change your test suite to chose the `akka.remote.netty.tcp.port` dynamically?

2017-03-28 07:31 UTC, ApacheBahir commented
Build successful

2017-03-28 07:31 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/38/

2017-03-28 07:32 UTC, sbcd90 commented
retest this please

2017-03-28 07:36 UTC, sbcd90 commented
Hi @ckadner , I have made `akka.remote.netty.tcp.port` dynamic.

2017-03-28 07:36 UTC, ApacheBahir commented
Build successful

2017-03-28 07:36 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/39/

2017-03-30 18:59 UTC, sbcd90 commented
Hi @ckadner , the test cases are skipped..any reason for that?

2017-03-30 22:26 UTC, ckadner commented
@sbcd90 -- your test cases ran fine, just with a lot of "noise".

http://169.45.79.58:8080/job/bahir_spark_pr_builder/38/consoleFull
```
00:27:23 [INFO] --- scalatest-maven-plugin:1.0:test (test) @ spark-sql-streaming-akka_2.11 ---
...
00:27:24 Discovery starting.
00:27:24 log4j:ERROR Could not read configuration file from URL [file:src/test/resources/log4j.properties].
00:27:24 java.io.FileNotFoundException: src/test/resources/log4j.properties (No such file or directory)
...
00:27:24 log4j:ERROR Ignoring configuration file [file:src/test/resources/log4j.properties].
...
00:27:24 Discovery completed in 698 milliseconds.
00:27:24 Run starting. Expected test count is: 5
00:27:24 StressTestAkkaSource:
00:27:24 Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
...
00:28:23 Run completed in 59 seconds, 534 milliseconds.
00:28:23 Total number of tests run: 5
00:28:23 Suites: completed 4, aborted 0
00:28:23 Tests: succeeded 5, failed 0, canceled 0, ignored 0, pending 0
00:28:23 All tests passed.
```

Could you add a `log4.j.properties` file in the test source folder to reduce the log verbosity?

2017-03-30 23:47 UTC, sbcd90 commented
retest this please

2017-03-30 23:47 UTC, sbcd90 commented
Hi @ckadner , Thanks for your reply. I have added `log4j.properties` in the test sources folder.

2017-03-30 23:51 UTC, ApacheBahir commented
Build successful

2017-03-30 23:51 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/42/

2017-03-31 03:38 UTC, ckadner commented
@sbcd90 -- Thanks, much better! To remove the remaining noise, I believe you would have to add a dependency to `akka-slf4j` in `sql-streaming-akka/pom.xml` and configure Akka to use the `akka.event.slf4j.Slf4jLogger` ...

```XML
    <dependency>
      <groupId>${akka.group}</groupId>
      <artifactId>akka-slf4j_${scala.binary.version}</artifactId>
      <version>${akka.version}</version>
    </dependency>
```

```Scala
akka.loggers.0 = "akka.event.slf4j.Slf4jLogger"
akka.log-dead-letters-during-shutdown = "off"
```

2017-03-31 19:02 UTC, sbcd90 commented
retest this please

2017-03-31 19:03 UTC, sbcd90 commented
Hi @ckadner , I have made the changes you mentioned to remove the remaining verbose. Please have a look.

2017-03-31 19:05 UTC, ApacheBahir commented
Build successful

2017-03-31 19:05 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/48/

2017-03-31 22:52 UTC, ckadner requested changes
minor not pick, please make sure to add new line characters at the end of files

2017-03-31 22:52 UTC, ckadner commented on sql-streaming-akka/src/main/assembly/assembly.xml
> +</assembly>
add new line

2017-03-31 22:52 UTC, ckadner commented on sql-streaming-akka/pom.xml
> +</project>
add new line

2017-03-31 22:52 UTC, ckadner commented on sql-streaming-akka/src/test/resources/feeder_actor.conf
> +}
add new line

2017-03-31 23:05 UTC, ckadner commented
@sbcd90 -- thanks for you continuous updates and sorry for the piecemeal review from my end  ... I started with your test cases since we were still in the process of fixing our Jenkins build setup. But your test cases are great now :-)

Perhaps more important, my first request to you should have been to add a README and examples so users can start using your connector without having to read through too much code ... i.e. please further follow the precedence set by `sql-streaming-mqtt`.

**Thank you!**

2017-04-02 07:18 UTC, sbcd90 commented
retest this please

2017-04-02 07:23 UTC, ApacheBahir commented
Build successful

2017-04-02 07:23 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/50/

2017-04-02 07:53 UTC, sbcd90 commented
Hi @ckadner , I have provided a README & examples as well..
Also, I have added a newline at the end of all the files..
plz have a look..

2017-04-05 17:42 UTC, sbcd90 commented
Hi @ckadner , I haven't seen any updates from you..plz let me know if anything else is required from my side...

2017-04-05 20:52 UTC, lresende commented on sql-streaming-akka/src/test/scala/org/apache/bahir/sql/streaming/akka/AkkaStreamSourceSuite.scala
> +
Would you please change to use Sparksession instead of directly instantiating a SQLContext.

2017-04-05 20:52 UTC, lresende commented on sql-streaming-akka/src/test/scala/org/apache/bahir/sql/streaming/akka/AkkaStreamSourceSuite.scala
> +
Would you please change to use Sparksession instead of directly instantiating a SQLContext.

2017-04-05 20:52 UTC, lresende commented on sql-streaming-akka/src/main/scala/org/apache/bahir/utils/BahirUtils.scala
> +
We should not duplicate these two classes on each extension. Could you create a jira for refactoring these into a bahir-common project that is shared with the other extensions.

2017-04-05 20:52 UTC, lresende commented on sql-streaming-akka/src/main/scala/org/apache/bahir/utils/Logging.scala
> +}
Similar comment as file above.

2017-04-05 21:05 UTC, lresende commented
Once we remove the deprecated api usages, we should be ready to merge unless someone has other comments.

2017-04-05 22:04 UTC, sbcd90 commented
retest this please

2017-04-05 22:08 UTC, ApacheBahir commented
Build successful

2017-04-05 22:08 UTC, ApacheBahir commented
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/53/

2017-04-05 22:24 UTC, sbcd90 commented
Hi @lresende , I have removed the usage of the deprecated api s
& also opened a jira issue named [BAHIR-103](https://issues.apache.org/jira/browse/BAHIR-103)
for refactoring the utils classes into bahir-common.

2017-04-05 22:58 UTC, ckadner commented
Thanks @lresende and @sbcd90 - LGTM

2017-04-06 15:07 UTC, closed without merging